### ISSUE TITLE
代码对应的论文

### ISSUE THREAD

**Issue by yyliu123** [kingbone9/LAIC2021#1]
你好，请问可以分享下您这个代码对应的论文吗？

**Comment by kingbone9** [comment]
投的中文，你要想看的话给我邮箱发份邮件，我传给你

**Comment by kingbone9** [comment]
> 你好，请问可以分享下您这个代码对应的论文吗？

会议推得期刊还要求论文进行一些修改，你可以先看一下，放在paper文件夹下了
